### ISSUE TITLE
Create a new dev env

### ISSUE THREAD

**Issue by sebastienbianco** [elefan-grenoble/gestion-compte#663]
Hi,

It is my first install of Elefan. It is on a clean env. Windows + Mariadb + Xampp (php 8.1) + Composer.

I've got this error : 

```
In Process.php line 143:

  [TypeError]
  Symfony\Component\Process\Process::__construct(): Argument #1 ($command) must be of type array, string given, ca
  lled in C:\elefan\gestion-compte\vendor\sensio\distribution-bundle\Composer\ScriptHandler.php on line 310


Exception trace:
  at phar://C:/composer/composer.phar/vendor/symfony/process/Process.php:143
 Symfony\Component\Process\Process->__construct() at C:\elefan\gestion-compte\vendor\sensio\distribution-bundle\Compo                          ser\ScriptHandler.php:310
 Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::executeBuildBootstrap() at C:\elefan\gestion-compte\vendor\                          sensio\distribution-bundle\Composer\ScriptHandler.php:88
 Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap() at phar://C:/composer/composer.phar/src/Co                          mposer/EventDispatcher/EventDispatcher.php:386
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar://C:/composer/composer.phar/src/Composer/E                          ventDispatcher/EventDispatcher.php:246
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar://C:/composer/composer.phar/src/Composer/EventDispatc                          her/EventDispatcher.php:107
 Composer\EventDispatcher\EventDispatcher->dispatch() at phar://C:/composer/composer.phar/src/Composer/EventDispatche                          r/EventDispatcher.php:226
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar://C:/composer/composer.phar/src/Composer/EventDispatc                          her/EventDispatcher.php:123
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar://C:/composer/composer.phar/src/Composer/Installe                          r.php:374
 Composer\Installer->run() at phar://C:/composer/composer.phar/src/Composer/Command/InstallCommand.php:144
 Composer\Command\InstallCommand->execute() at phar://C:/composer/composer.phar/vendor/symfony/console/Command/Comman                          d.php:298
 Symfony\Component\Console\Command\Command->run() at phar://C:/composer/composer.phar/vendor/symfony/console/Applicat                          ion.php:1028
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/composer/composer.phar/vendor/symfony/console/App                          lication.php:299
 Symfony\Component\Console\Application->doRun() at phar://C:/composer/composer.phar/src/Composer/Console/Application.                          php:375
 Composer\Console\Application->doRun() at phar://C:/composer/composer.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar://C:/composer/composer.phar/src/Composer/Console/Application.ph                          p:139
 Composer\Console\Application->run() at phar://C:/composer/composer.phar/bin/composer:88
 require() at C:\composer\composer.phar:29

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-                          dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [                          -o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER                          -PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

```
Here is the paramater file (I added the .txt extension to be allowed to upload to git) :
[parameters.yml.txt](https://github.com/elefan-grenoble/gestion-compte/files/10098744/parameters.yml.txt)

I've tryied last week with php 7.4. I also try to install on wsl/ubuntu 22/php 7.4 (composer unfonctionnal)/php 8.

I few weeks ago, I succeed to build and run but I never get the bundle package (bootstrap, jquery, etc), so the app were unusable That's why I restart all with new version... And It's worst :(

**Comment by sebastienbianco** [comment]
Nouvelle erreur avec la version 2.2.17 de composer : 

```
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception


  [RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command:


  Fatal error: During inheritance of ArrayAccess: Uncaught Error: Class "Symfony\Component\VarDumper\Cloner\Data" not
   found in C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\AbstractCloner.php
  :238
  Stack trace:
  #0 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Formatter\VarDumperFormatter.php(31):
   Symfony\Component\VarDumper\Cloner\AbstractCloner->cloneVar(Array)
  #1 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Handler\ServerLogHandler.php(109): Sy
  mfony\Bridge\Monolog\Formatter\VarDumperFormatter->format(Array)
  #2 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Handler\ServerLogHandler.php(58): Sym
  fony\Bridge\Monolog\Handler\ServerLogHandler->formatRecord(Array)
  #3 C:\elefan\gestion-compte\vendor\monolog\monolog\src\Monolog\Logger.php(344): Symfony\Bridge\Monolog\Handler\Serv
  erLogHandler->handle(Array)
  #4 C:\elefan\gestion-compte\vendor\monolog\monolog\src\Monolog\Logger.php(614): Monolog\Logger->addRecord(200, 'Dep
  recated: Ret...', Array)
  #5 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php(532): Monolog\Logge
  r->log(200, 'Deprecated: Ret...', Array)
  #6 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\AbstractCloner.php(227):
  Symfony\Component\Debug\ErrorHandler->handleError(8192, 'Return type of ...', 'C:\\elefan\\gesti...', 141, Array)
  #7 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\Data.php(19): Symfony\Com
  ponent\VarDumper\Cloner\AbstractCloner->Symfony\Component\VarDumper\Cloner\{closure}(8192, 'Return type of ...', 'C
  :\\elefan\\gesti...', 141)
  #8 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php(155): include('
  C:\\elefan\\gesti...')
  #9 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\AbstractCloner.php(238):
  Symfony\Component\Debug\DebugClassLoader->loadClass('Symfony\\Compone...')
  #10 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Formatter\VarDumperFormatter.php(31)
  : Symfony\Component\VarDumper\Cloner\AbstractCloner->cloneVar(Array)
  #11 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Handler\ServerLogHandler.php(109): S
  ymfony\Bridge\Monolog\Formatter\VarDumperFormatter->format(Array)
  #12 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Handler\ServerLogHandler.php(58): Sy
  mfony\Bridge\Monolog\Handler\ServerLogHandler->formatRecord(Array)
  #13 C:\elefan\gestion-compte\vendor\monolog\monolog\src\Monolog\Logger.php(344): Symfony\Bridge\Monolog\Handler\Ser
  verLogHandler->handle(Array)
  #14 C:\elefan\gestion-compte\vendor\monolog\monolog\src\Monolog\Logger.php(614): Monolog\Logger->addRecord(200, 'De
  precated: App...', Array)
  #15 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php(249): Monolog\Logg
  er->log(200, 'Deprecated: App...', Array)
  #16 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php(201): Symfony\Comp
  onent\Debug\ErrorHandler->setLoggers(Array)
  #17 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\DebugHandlersLis
  tener.php(83): Symfony\Component\Debug\ErrorHandler->setDefaultLogger(Object(Symfony\Bridge\Monolog\Logger), -1)
  #18 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\WrappedListener.php
  (115): Symfony\Component\HttpKernel\EventListener\DebugHandlersListener->configure(Object(Symfony\Component\Console
  \Event\ConsoleCommandEvent), 'console.command', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)
  )
  #19 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(214):
   Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\Console\Event\ConsoleCo
  mmandEvent), 'console.command', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
  #20 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(44):
  Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'console.command', Object(Symfony\Component\Co
  nsole\Event\ConsoleCommandEvent))
  #21 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\TraceableEventDispa
  tcher.php(143): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('console.command', Object(Symfony\Compo
  nent\Console\Event\ConsoleCommandEvent))
  #22 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(1007): Symfony\Co
  mponent\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('console.command', Object(Symfony\Component\Consol
  e\Event\ConsoleCommandEvent))
  #23 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(86):
   Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Bundle\FrameworkBundle\Command\CacheClearComman
  d), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #24 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(255): Symfony\Bun
  dle\FrameworkBundle\Console\Application->doRunCommand(Object(Symfony\Bundle\FrameworkBundle\Command\CacheClearComma
  nd), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #25 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(74):
   Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Com
  ponent\Console\Output\ConsoleOutput))
  #26 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(148): Symfony\Bun
  dle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Co
  mponent\Console\Output\ConsoleOutput))
  #27 C:\elefan\gestion-compte\bin\console(27): Symfony\Component\Console\Application->run(Object(Symfony\Component\C
  onsole\Input\ArgvInput))
  #28 {main} in C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\Data.php on li
  ne 19


  PHP Fatal error:  During inheritance of ArrayAccess: Uncaught Error: Class "Symfony\Component\VarDumper\Cloner\Data
  " not found in C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\AbstractClone
  r.php:238
  Stack trace:
  #0 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Formatter\VarDumperFormatter.php(31):
   Symfony\Component\VarDumper\Cloner\AbstractCloner->cloneVar(Array)
  #1 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Handler\ServerLogHandler.php(109): Sy
  mfony\Bridge\Monolog\Formatter\VarDumperFormatter->format(Array)
  #2 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Handler\ServerLogHandler.php(58): Sym
  fony\Bridge\Monolog\Handler\ServerLogHandler->formatRecord(Array)
  #3 C:\elefan\gestion-compte\vendor\monolog\monolog\src\Monolog\Logger.php(344): Symfony\Bridge\Monolog\Handler\Serv
  erLogHandler->handle(Array)
  #4 C:\elefan\gestion-compte\vendor\monolog\monolog\src\Monolog\Logger.php(614): Monolog\Logger->addRecord(200, 'Dep
  recated: Ret...', Array)
  #5 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php(532): Monolog\Logge
  r->log(200, 'Deprecated: Ret...', Array)
  #6 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\AbstractCloner.php(227):
  Symfony\Component\Debug\ErrorHandler->handleError(8192, 'Return type of ...', 'C:\\elefan\\gesti...', 141, Array)
  #7 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\Data.php(19): Symfony\Com
  ponent\VarDumper\Cloner\AbstractCloner->Symfony\Component\VarDumper\Cloner\{closure}(8192, 'Return type of ...', 'C
  :\\elefan\\gesti...', 141)
  #8 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php(155): include('
  C:\\elefan\\gesti...')
  #9 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\AbstractCloner.php(238):
  Symfony\Component\Debug\DebugClassLoader->loadClass('Symfony\\Compone...')
  #10 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Formatter\VarDumperFormatter.php(31)
  : Symfony\Component\VarDumper\Cloner\AbstractCloner->cloneVar(Array)
  #11 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Handler\ServerLogHandler.php(109): S
  ymfony\Bridge\Monolog\Formatter\VarDumperFormatter->format(Array)
  #12 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Handler\ServerLogHandler.php(58): Sy
  mfony\Bridge\Monolog\Handler\ServerLogHandler->formatRecord(Array)
  #13 C:\elefan\gestion-compte\vendor\monolog\monolog\src\Monolog\Logger.php(344): Symfony\Bridge\Monolog\Handler\Ser
  verLogHandler->handle(Array)
  #14 C:\elefan\gestion-compte\vendor\monolog\monolog\src\Monolog\Logger.php(614): Monolog\Logger->addRecord(200, 'De
  precated: App...', Array)
  #15 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php(249): Monolog\Logg
  er->log(200, 'Deprecated: App...', Array)
  #16 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php(201): Symfony\Comp
  onent\Debug\ErrorHandler->setLoggers(Array)
  #17 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\DebugHandlersLis
  tener.php(83): Symfony\Component\Debug\ErrorHandler->setDefaultLogger(Object(Symfony\Bridge\Monolog\Logger), -1)
  #18 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\WrappedListener.php
  (115): Symfony\Component\HttpKernel\EventListener\DebugHandlersListener->configure(Object(Symfony\Component\Console
  \Event\ConsoleCommandEvent), 'console.command', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)
  )
  #19 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(214):
   Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\Console\Event\ConsoleCo
  mmandEvent), 'console.command', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
  #20 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(44):
  Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'console.command', Object(Symfony\Component\Co
  nsole\Event\ConsoleCommandEvent))
  #21 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\TraceableEventDispa
  tcher.php(143): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('console.command', Object(Symfony\Compo
  nent\Console\Event\ConsoleCommandEvent))
  #22 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(1007): Symfony\Co
  mponent\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('console.command', Object(Symfony\Component\Consol
  e\Event\ConsoleCommandEvent))
  #23 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(86):
   Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Bundle\FrameworkBundle\Command\CacheClearComman
  d), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #24 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(255): Symfony\Bun
  dle\FrameworkBundle\Console\Application->doRunCommand(Object(Symfony\Bundle\FrameworkBundle\Command\CacheClearComma
  nd), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #25 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(74):
   Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Com
  ponent\Console\Output\ConsoleOutput))
  #26 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(148): Symfony\Bun
  dle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Co
  mponent\Console\Output\ConsoleOutput))
  #27 C:\elefan\gestion-compte\bin\console(27): Symfony\Component\Console\Application->run(Object(Symfony\Component\C
  onsole\Input\ArgvInput))
  #28 {main} in C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\Data.php on li
  ne 19

  In Data.php line 19:


    Error: During inheritance of ArrayAccess: Uncaught Error: Class "Symfony\Component\VarDumper\Cloner\Data" not fou
  nd
     in C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\AbstractCloner.php:238

    Stack trace:

    #0 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Formatter\VarDumperFormatter.php(31
  ):
     Symfony\Component\VarDumper\Cloner\AbstractCloner->cloneVar(Array)

    #1 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Handler\ServerLogHandler.php(109):
  Sy
    mfony\Bridge\Monolog\Formatter\VarDumperFormatter->format(Array)

    #2 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Handler\ServerLogHandler.php(58): S
  ym
    fony\Bridge\Monolog\Handler\ServerLogHandler->formatRecord(Array)

    #3 C:\elefan\gestion-compte\vendor\monolog\monolog\src\Monolog\Logger.php(344): Symfony\Bridge\Monolog\Handler\Se
  rv
    erLogHandler->handle(Array)

    #4 C:\elefan\gestion-compte\vendor\monolog\monolog\src\Monolog\Logger.php(614): Monolog\Logger->addRecord(200, 'D
  ep
    recated: Ret...', Array)

    #5 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php(532): Monolog\Log
  ge
    r->log(200, 'Deprecated: Ret...', Array)

    #6 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\AbstractCloner.php(227)
  :
    Symfony\Component\Debug\ErrorHandler->handleError(8192, 'Return type of ...', 'C:\\elefan\\gesti...', 141, Array)

    #7 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\Data.php(19): Symfony\C
  om
    ponent\VarDumper\Cloner\AbstractCloner->Symfony\Component\VarDumper\Cloner\{closure}(8192, 'Return type of ...',
  'C
    :\\elefan\\gesti...', 141)

    #8 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php(155): include
  ('
    C:\\elefan\\gesti...')

    #9 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\VarDumper\Cloner\AbstractCloner.php(238)
  :
    Symfony\Component\Debug\DebugClassLoader->loadClass('Symfony\\Compone...')

    #10 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Formatter\VarDumperFormatter.php(3
  1)
    : Symfony\Component\VarDumper\Cloner\AbstractCloner->cloneVar(Array)

    #11 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Handler\ServerLogHandler.php(109):
   S
    ymfony\Bridge\Monolog\Formatter\VarDumperFormatter->format(Array)

    #12 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bridge\Monolog\Handler\ServerLogHandler.php(58):
  Sy
    mfony\Bridge\Monolog\Handler\ServerLogHandler->formatRecord(Array)

    #13 C:\elefan\gestion-compte\vendor\monolog\monolog\src\Monolog\Logger.php(344): Symfony\Bridge\Monolog\Handler\S
  er
    verLogHandler->handle(Array)

    #14 C:\elefan\gestion-compte\vendor\monolog\monolog\src\Monolog\Logger.php(614): Monolog\Logger->addRecord(200, '
  De
    precated: App...', Array)

    #15 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php(249): Monolog\Lo
  gg
    er->log(200, 'Deprecated: App...', Array)

    #16 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php(201): Symfony\Co
  mp
    onent\Debug\ErrorHandler->setLoggers(Array)

    #17 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\DebugHandlersL
  is
    tener.php(83): Symfony\Component\Debug\ErrorHandler->setDefaultLogger(Object(Symfony\Bridge\Monolog\Logger), -1)

    #18 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\WrappedListener.p
  hp
    (115): Symfony\Component\HttpKernel\EventListener\DebugHandlersListener->configure(Object(Symfony\Component\Conso
  le
    \Event\ConsoleCommandEvent), 'console.command', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatche
  r)
    )

    #19 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(214
  ):
     Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\Console\Event\Console
  Co
    mmandEvent), 'console.command', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))

    #20 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(44)
  :
    Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'console.command', Object(Symfony\Component\
  Co
    nsole\Event\ConsoleCommandEvent))

    #21 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\TraceableEventDis
  pa
    tcher.php(143): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('console.command', Object(Symfony\Com
  po
    nent\Console\Event\ConsoleCommandEvent))

    #22 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(1007): Symfony\
  Co
    mponent\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('console.command', Object(Symfony\Component\Cons
  ol
    e\Event\ConsoleCommandEvent))

    #23 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(86
  ):
     Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Bundle\FrameworkBundle\Command\CacheClearComm
  an
    d), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

    #24 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(255): Symfony\B
  un
    dle\FrameworkBundle\Console\Application->doRunCommand(Object(Symfony\Bundle\FrameworkBundle\Command\CacheClearCom
  ma
    nd), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

    #25 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(74
  ):
     Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\C
  om
    ponent\Console\Output\ConsoleOutput))

    #26 C:\elefan\gestion-compte\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(148): Symfony\B
  un
    dle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\
  Co
    mponent\Console\Output\ConsoleOutput))

    #27 C:\elefan\gestion-compte\bin\console(27): Symfony\Component\Console\Application->run(Object(Symfony\Component
  \C
    onsole\Input\ArgvInput))

    #28 {main}




  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--
  ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>


install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...

```

Est-ce compatible PHP 8.1 ?

**Comment by sebastienbianco** [comment]
En PHP 7.4.33 çà fonctionne. La réponse est donc probablement : non

**Comment by symartin** [comment]
Salut, 
j'ai écrit un draft de documentation sur le wiki pour facilité l’installation d'un environnement de développent : https://github.com/elefan-grenoble/gestion-compte/wiki/Development-environment-on-Windows

il y a qq petits pièges, comme activer la compatibilité avec UTF8 par exemple :)
